NAVER_CUSTOMER_ID = "1806006"
NAVER_API_KEY = "0100000000bfe8af5c5eccf0c5bb0ebe9f23b93d134..."
NAVER_SECRET_KEY = "AQAAAACwGKzEw6JVrOFRIlWWRXwUc1aiYBGCg3Org..."
DOMEGGOOK_API_KEY = "097fc5678c5b66bf0b7dd2be8d1b7fdb"
